spring:
  activemq:
    broker-url: tcp://localhost:61616 #\u6307\u5B9AActiveMQ broker\u7684URL\uFF0C\u9ED8\u8BA4\u81EA\u52A8\u751F\u6210.
    user: admin #\u6307\u5B9Abroker\u7684\u7528\u6237
    password: admin #\u6307\u5B9Abroker\u7684\u5BC6\u7801.
    in-memory: true #\u662F\u5426\u662F\u5185\u5B58\u6A21\u5F0F\uFF0C\u9ED8\u8BA4\u4E3Atrue.
    pool:
      enabled: false #\u662F\u5426\u521B\u5EFAPooledConnectionFactory\uFF0C\u800C\u975EConnectionFactory\uFF0C\u9ED8\u8BA4false